FROM alpine-jdk:base
LABEL maintainer="Oussama_Imen"
RUN apk --no-cache add netcat-openbsd
COPY discovery-service/target/discovery-service-0.0.1-SNAPSHOT.jar /opt/lib/
COPY discoveryservice_wait-fot-it.sh /opt/bin/
RUN chmod 755 /opt/bin/discoveryservice_wait-for-it.sh
EXPOSE 8761
